# Use the official NGINX image from Docker Hub
FROM nginx:latest

# Copy the contents of the public folder to the NGINX html directory
COPY public /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start NGINX
CMD ["nginx", "-g", "daemon off;"]